### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by razvantomegea** [browser-actions/publish-firefox-addon#25]
I tried to release an addon, but I got timeout error. The publish failed. Did not appear in store

```
Run browser-actions/release-firefox-addon@latest
Addon "firefox-extension-build.zip" has been uploaded with UUID "f94412f5549d4e1aa4fe464365a10db5"
Error: Error: timed-out waiting for addon to be processed
```

```
- name: Publish to Firefox Add-ons
        id: publish
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: ${{ secrets.ADDON_ID }}
          addon-path: firefox-extension-build.zip
          source-path: wallet.zip
          auth-api-issuer: ${{ secrets.AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.AUTH_API_SECRET }}
          release-note: ${{ steps.extract-notes.outputs.release_notes || github.event.release.body || 'New release' }}
          approval-note: 'Build commands used for this extension: yarn install, export NODE_OPTIONS=-max-old-space-size=8192 yarn build-extension-firefox'
```
